// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrzkgyscaloxgmaajbau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yemtneXNjYWxveGdtYWFqYmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3ODQ0MDksImV4cCI6MjA4ODM2MDQwOX0.bc02ztYBoOHGKwo3fC-0BoXVcRJkF2LG1RlYvWvD94A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});